### ISSUE TITLE
Optional Template and Controller when Generating Routes

### ISSUE THREAD

**Issue by scott-mcpherson** [iron-meteor/iron-cli#101]
Probably one of my most used commands with em, was the route generator. I liked having the associated template and controller automatically generated.

I'm thinking that might be a good option to have in the config file.

**Comment by scott-mcpherson** [comment]
What do you think about adding something like this to the config file @cmather :
```json
{
    "generators": {
        "route": {
            "controller": true,
            "template": true,
        }
    ...
}
```
When generating a route, a controller and template would also be generated.

**Comment by lirbank** [comment]
+1

**Comment by scott-mcpherson** [comment]
I've almost got it working @lirbank . I'm kind of stuck [here on line 54](https://github.com/iron-meteor/iron-cli/commit/c77fc541c6a5e97a5a1975eb67670843cdab9681). I've got the generators in an array and I just need to figure out how to loop through them in a synchronous manner using something like fibers. 

If you have any experience with this and you have a minute, could you take a quick look.

https://github.com/iron-meteor/iron-cli/commit/c77fc541c6a5e97a5a1975eb67670843cdab9681

**Comment by cmather** [comment]
Btw all the file methods in tools are already synchronous.

**Comment by cmather** [comment]
Is this is sorted?

**Comment by scott-mcpherson** [comment]
Yep
