### ISSUE TITLE
Best practice: iron migrate and .git folder question

### ISSUE THREAD

**Issue by bojicas** [iron-meteor/iron-cli#102]
Just did an ```iron migrate``` into an existing ```em``` project. All fine, but noticed that the ```.git``` (root) folder goes under ```app```.

My question:

What is the recommended place to keep root git folder: ```<project_root>``` or ```<project_root>/app``` ?

If the answer is ```<project_root>```, maybe we can make iron-cli automatically move ```.git``` folder up one level.

**Comment by scott-mcpherson** [comment]
I guess it's really a matter of preference. 

I personally prefer to keep it under app. 
That automatically keeps my settings.json out of GitHub, which sometimes contains secret keys.

But for migration purposes, it probably makes sense to keep the git folder under the app's root.

**Comment by bojicas** [comment]
Thank you for the answer. It makes sense to keep ```.git``` folder under ```<project_root>/app```, as the possible secrets will stay out of repository (or as you said, let the user decide).

However, I believe that ```.iron``` folder that contains iron-cli settings should go in this case under ```<project_app>/app``` folder too, as probably this is something we want to keep them under version control. What do you think?

**Comment by cmather** [comment]
Oh interesting. This was actually just an oversight on my part (i.e. I didn't *think* about the git folder going into app). I actually think it should be in the project folder. Secret keys should be on the production server, not in your project folder at all. Pull request?

**Comment by cmather** [comment]
BTW, I would hope at some point that Meteor would recognize that not all folders in the project should partake in the bundle process (i.e. there really should be an 'app' folder in a regular meteor project). That's the only reason we moved the meteor stuff into 'app'.

**Comment by scott-mcpherson** [comment]
I was thinking it would be kind of cool to have both the development and production settings under the config folder, and eventually work a deploy command into iron. That might be a little out there though. And even then, we could always add a gitignore file to protect production settings.

**Comment by bojicas** [comment]
Peeking at Ruby on Rails framework: there is a ```config/secrets.yml``` file that contains things like database usernames and passwords or other *secrets* for various environments (development, production), file which is normally .gitignored. In the same time the same ```config``` folder contains other useful configuration files that go into versioning system.

Extrapolating, I think that ```.git``` in the ```<project_root>``` and .gitignoring config files that contain secrets is the best practice after all.

**Comment by bojicas** [comment]
Sorry if I am too verbose, just one more reason I found in favor of ```.git``` in ```<project_root>```: my shell, ```zsh``` is configured to give feedback on which branch I am and if there are any pending changes. In the end ```iron``` replaces the need of changing into ```app``` and launching ```meteor``` relating commands from there. In the same way, it would be nice to have git related info from the ```<project_root>```, too.

**Comment by scott-mcpherson** [comment]
That's a good point @bojicas . It's much more convenient to not have to cd into the app.

**Comment by cmather** [comment]
Yep for production one approach is to symlink a config directory into the project folder on deployment. That way the production config can just exist on the deployment server.

**Comment by scott-mcpherson** [comment]
That sounds like a good feed video @cmather . 

I've been using Meteor Up and the production settings are stored in the Meteor Up directory. 

I still think it would be kind of cool to have a deploy script baked right in to iron.
