### ISSUE TITLE
Define a Port in env.sh

### ISSUE THREAD

**Issue by scott-mcpherson** [iron-meteor/iron-cli#104]
It would nice to be able to define a port environment variable in env.sh, and have iron automatically run the app with that port.

I could be wrong, but believe when were using the npm package to load env.sh, this was possible.

**Comment by cmather** [comment]
Does meteor honor a PORT env variable? Any environment variables can be exported in the env.sh file will be sourced before running the meteor command. So it should just work, so long as Meteor actually uses the env variable. Any settings can be passed along as options to the run command. Am I missing something?

**Comment by cmather** [comment]
See line 30 of lib/commands/run.js

**Comment by scott-mcpherson** [comment]
For some reason I was thinking I could do something like `export PORT=8000`, and get the app to run at that port when running the app with the iron command. I guess not though.

**Comment by cmather** [comment]
If it works with the regular meteor command it will work with iron. Meteor might not respect the PORT env variable in development.
