### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-cli#112]
Hey @scott-mcpherson, I'm going to put out a release in a few seconds which got me thinking about branches. Perhaps we try to keep the master branch ready for deployment, and use our own working branches for ongoing development. That way we can deploy the master branch and pull things in at a snapshot in time. Alternatively we could just create a devel branch that we both work on, but I figured it was too complicated for a small project.

**Comment by cmather** [comment]
Also, checkout git-extras. I'm using it to auto generate history and an authors list. I'm also going to create a release script so we can just do:

```> git release 1.1.0```

https://github.com/tj/git-extras

**Comment by cmather** [comment]
Okay 1.1.0 is released!

**Comment by scott-mcpherson** [comment]
I'm good with whatever workflow you want to use... But I do kind of like having a devel branch that I can pull from before I do any work on it. And then push to it when I'm done working on it. 

If we use our own working branches (I'm assuming they're local), how do we keep the code in sync?

git-extras looks cool. I'll checkout the screencast later on today.
And a release script would be awesome!

Excellent work on releasing 1.1.0!

**Comment by cmather** [comment]
now 1.1.1 :)
