### ISSUE TITLE
iron run uses over 100% cpu

### ISSUE THREAD

**Issue by chrisbutler** [iron-meteor/iron-cli#120]
but starting the server with `meteor run` uses a normal amount of resources

i'm on OS X 10.9.5 and node 0.12.0

**Comment by cmather** [comment]
hmm that's no good. any clues?

**Comment by chrisbutler** [comment]
any ideas on what to look for/where?

**Comment by cmather** [comment]
Look in the tools/meteor file at the function that invokes a meteor command

**Comment by yoamomonstruos** [comment]
Yeah, this is using crazy cpu for me too, like 170% or something.

**Comment by vieko** [comment]
Second this... solid 170% CPU usage.

**Comment by cmather** [comment]
Hey folks, I will try to look at this later today or tonight. Is it with all commands?

**Comment by vieko** [comment]
booting the app with `iron` or `iron run` does it for me... haven't monitored with the other commands yet.

**Comment by cmather** [comment]
I'm seeing this behavior using `iron run` too. But I'm not sure yet what's causing it.

**Comment by vieko** [comment]
Earlier today, I saw an unrelated post talking about a file watcher been the culprit of a similar issue… I’ll dig through my history and try to find it...
On March 19, 2015 at 5:45:34 PM, Chris Mather (notifications@github.com) wrote:

I'm seeing this behavior using iron run too. But I'm not sure yet what's causing it.

**Comment by cmather** [comment]
Cool. I'm having trouble figuring out why running the meteor command from nodejs `spawn()` would cause an issue, when running the `meteor run` command directly does not cause an issue. It seems to also happen on the `meteor shell` command. I'm looking through changes to meteor tools/commands.js to see if anything there might be causing the issue.

**Comment by cmather** [comment]
Have folks noticed this from the beginning, or only with the latest version of Meteor?

**Comment by cmather** [comment]
Looks like it might have something to do with the stdio option to the spawn command. From inside an app directory in a node session:

```javascript
> spawn = require('child_process').spawn;
> child = spawn('meteor', [] {}); // check cpu seems fine
> child.kill();

> child = spawn('meteor', [], {stdio: 'inherit'}); // cpu spikes
> child.kill();
```

pondering...

**Comment by cmather** [comment]
I think I figured it out. Can people test from the `bug/cpu` branch. See the above commit for the change that I think fixes this.

**Comment by vieko** [comment]
I've just started using the cli (love it) so can't comment on previous versions... Will try the bug branch shortly!

On Mar 19, 2015, at 6:49 PM, Chris Mather <notifications@github.com> wrote:

Have folks noticed this from the beginning, or only with the latest version of Meteor?

**Comment by spicemix** [comment]
If anyone wants a workaround in the time being, there's this:

[`cputhrottle`](http://www.willnolan.com/cputhrottle/cputhrottle.html)

`pgrep node` to get the PID (the second node PID does it for me)

**Comment by cmather** [comment]
Well before using a workaround try the fix :-)

**Comment by chrisbutler** [comment]
@cmather :+1:

**Comment by vieko** [comment]
Works wonders and with normal CPU usage under both 1.0.4.1 and 1.0.3.2... thank you!

**Comment by cmather** [comment]
ok cool. i'll do a scan of the other bugs and try to put out a new release today. thanks for tracking this down.
