### ISSUE TITLE
How to use with node-inspector?

### ISSUE THREAD

**Issue by josephdburdick** [iron-meteor/iron-cli#122]
How does run iron-cli commands while inspecting the back-end with node-inspector? Is it expected that while debugging the backend that straight meteor cli commands be used or is there anyway to trigger iron + node-inspector at the same time, with 1 command?

**Comment by cmather** [comment]
It should just work with the iron command the same way it does with the meteor command. Is it not working? I think I'm proxying command line arguments to the meteor command along with the current environment but I might have missed a spot. Check lib/tools/meteor.js

**Comment by josephdburdick** [comment]
@cmather Hey thanks for directing me to the source. I read https://github.com/iron-meteor/iron-cli/blob/master/lib/tools/meteor.js#L100 and realized that debug is a command accessible via iron-cli and it runs inside the app directory. I kept following instructions for node-inspector by running it in another terminal window.

I might fork your README and create a pull request to make this more explicit for other people since the 2-for-1, not needing another terminal window to trigger debugging is a total bonus in my eyes. I assume you still need to npm install -g node-inspector yourself though, right?
