### ISSUE TITLE
Package-oriented structure supported by iron

### ISSUE THREAD

**Issue by wolasss** [iron-meteor/iron-cli#123]
Hello!

Some people like to create meteor application with packages instead of root-structure approach (which all files/dirs land in root dir), so that every logical unit is a separate package. It would be cool for having a support for this approach as well, instead of enforcing a user to structure an app only this way. 

What do you think of such idea? Should I work on this and send a pull request?

**Comment by cmather** [comment]
I think the feature should be the ability to plug in additional generators or override existing generators.

**Comment by chrisbutler** [comment]
@wolasss i added a basic package generator. let me know what you think and if you have any suggestions
