### ISSUE TITLE
[Bug] Deploy to Meteor gives "file not found (settings file)"

### ISSUE THREAD

**Issue by lirbank** [iron-meteor/iron-cli#125]
From the project dir:
```
$ cd myproject
$ iron deploy asite.meteor.com --settings config/development/settings.json 
> meteor deploy asite.meteor.com --settings config/development/settings.json

Deploying to asite.meteor.com.               
                                              
Errors prevented deploying:
While preparing to deploy:                    
config/development/settings.json: file not found (settings file)
```

However it works if using `meteor` directly in the app/ dir:
```
cd myproject/app/
$ meteor deploy asite.meteor.com --settings config/development/settings.json 
```

**Comment by cmather** [comment]
Oh interesting. Any time to look into the deploy source code to see why this is? My guess is that meteor is looking for a config directory under the app directory and not finding it. Does it work if you use a full path (e.g.  /Users/x/src/proj/config/development/settings.json)

**Comment by cmather** [comment]
To fix, we might have to override the deploy command and expand the path before passing it to meteor. Or submit a patch. But let's verify the problem first.

**Comment by lirbank** [comment]
I'll investigate shortly and post what I find here!

**Comment by chrisbutler** [comment]
@lirbank i don't think that

    $ meteor deploy asite.meteor.com --settings config/development/settings.json

would be working unless the ```config/``` directory was located inside of your ```app/``` directory

```iron deploy``` has always worked if you specified an absolute path to ```settings.json``` as @cmather mentioned above, but i just added a command that does this for you

i'm going to release a new version shortly, let me know if it resolves this issue for you

**Comment by lirbank** [comment]
I mostly don't use Meteor deploy, this was just something I found when I was experimenting with something so I figured I'd report it.

It's been a while so I can't be sure, but I have a feeling I've manually created the examples above so maybe the missing "../" in the second example is just a type. Was pretty sure I double checked it all, but could of course be wrong. I'll try it and let you know if it's still there (

**Comment by lirbank** [comment]
Tried this again just now:
```
$ iron create testapp
$ cd testapp/
$ meteor login
Username: ***
Password:                                     
                                              
Logged in as ***. Thanks for being a Meteor developer!
$ iron deploy mikael123.meteor.com --settings config/development/settings.json 
> meteor deploy mikael123.meteor.com --settings config/development/settings.json

Deploying to mikael123.meteor.com.


Errors prevented deploying:

While preparing to deploy:
config/development/settings.json: file not found (settings file)


Mikaels-MacBook-Pro:testapp mikaellirbank$ cd app/
Mikaels-MacBook-Pro:app mikaellirbank$ meteor deploy mikael123.meteor.com --settings ../config/development/settings.json 
Deploying to mikael123.meteor.com.            
Now serving at http://mikael123.meteor.com    
```

**Comment by lirbank** [comment]
Using a path relative path to meteor for the config file works though:
```
$ iron deploy mikael123.meteor.com --settings ../config/development/settings.json 
```

**Comment by lirbank** [comment]
Just upgraded to the latest Iron-cli (1.3.1), now I get:
```
$ iron deploy mikael123.meteor.com --settings config/development/settings.json 
> meteor deploy mikael123.meteor.com --settings config/development/settings.json --settings config/development/settings.json
deploy: can only take one --settings option.

Try 'meteor help deploy' for help.
```

**Comment by lirbank** [comment]
@chrisbutler Most people probably don't use meteor deploy so not sure it's a prio to fix it, but the issue should probably remain open (see my tests above).

**Comment by chrisbutler** [comment]
@lirbank what about just iron deploy? it should use development settings automatically, the idea being that you don't ever pass a path, just an environment

without actually looking into the code, i can guess where passing your own relative path can be a problem because i don't think we convert it

**Comment by lirbank** [comment]
Aha, didn't know that. I guess it makes sense, but if someone provides a settings file, it should probably override the default settings file assumed by Iron-cli. Anyhow, that would be an architectural/product discussion so think we should keep this issue closed :)
