### ISSUE TITLE
Coffeescript & Jade

### ISSUE THREAD

**Issue by ryenbeatty** [iron-meteor/iron-cli#127]
Hi!

I'd be interested in helping set up coffeescript/jade support, any thoughts on the best way to go about this?

**Comment by cmather** [comment]
Hey @ryenbeatty, cool! I'll show you a couple of pointers:

* For the project and create a branch to work on like "feature/jade" then you can invite people to check out various commits in the branch or submit a PR from the branch.
* lib/templates: This is where all the template folders and files are. By 'templates' I mean files that iron-cli converts into files in your meteor project when you use the various command line generators. 
* For example, all of the files associated with generating a "stylesheet" resource are in the lib/templates/stylesheet folder.
* Notice in the folders there are multiple extensions after the .css. For example there's .css.less, .css.scss, .css.styl. That last part of the extension we call an "engine". Whichever engine you're using for the given type of file is the template that will be used.
* The default engines for the project are in the .iron/config.json file whose template is here: https://github.com/iron-meteor/iron-cli/blob/master/lib/templates/project/.iron/config.json. These values are configurable at project creation time, or any time after by editing the file directly.
* This file is loaded using a config class which is located here: https://github.com/iron-meteor/iron-cli/blob/master/lib/config.js. Notice there is an object of supported engines on line 28. That's how we know which engines have all their corresponding template files.

So the steps to add an engine are:

1. Add the templates to each of the template folders
2. Add to the list of supported engines in the lib/config.js file
3. Test all of the generators

PS the templating engine is ejs

Hope this helps to get you started

**Comment by ryenbeatty** [comment]
Hey @cmather, seems like github no longer has notifications, as I completely was not aware you had replied! Thanks for the detailed instructions, should be enough to get started adding support for a couple more syntaxes :)

**Comment by chrisbutler** [comment]
@ryenbeatty coffeescript and jade are now directly supported

**Comment by ryenbeatty** [comment]
Nice one @chrisbutler
