### ISSUE TITLE
sass support?

### ISSUE THREAD

**Issue by rami2929** [iron-meteor/iron-cli#135]
Looks like there is no sass support (--css=sass). Any plan to include sass in the future by any chance?

**Comment by mitzip** [comment]
I'd just read about where they were asking for help adding engines here https://github.com/iron-meteor/iron-cli/blob/master/README.md#coffeescript-support

I think this is where you can do it...
https://github.com/iron-meteor/iron-cli/blob/master/lib/config.js#L31

**Comment by scottmcpherson** [comment]
@rami2929 Are you using .sass or .scss? If you're using .scss you have to be explicit `--css=scss`.

**Comment by scottmcpherson** [comment]
I'm going to close this for now but let me know if you were wanting .sass files (I think .scss is the more common one).

**Comment by rami2929** [comment]
sorry for late reply, I'm using .sass. thanks.
