### ISSUE TITLE
"iron run android-device" adds param twice

### ISSUE THREAD

**Issue by gerwinbrunner** [iron-meteor/iron-cli#140]
Hi,

if I call `iron run android-device`

I expect to get this call
```
meteor run --settings ../app-mobile/config/development/settings.json --port 3007 android-device
```

but it actually calls this 
```
meteor run android-device --settings ../app-mobile/config/development/settings.json --port 3007 android-device
```

So somehow the parameters after the run command get added twice to the target call.

Cheers,
Gerwin

**Comment by mitzip** [comment]
The first "andriod-device" is being passed from here 

https://github.com/iron-meteor/iron-cli/blob/88184b7331db3a5f555e23ce6e1bcd7c2abcf1ab/lib/tools/meteor.js#L137

to here where the settings option is being appended to it...

https://github.com/iron-meteor/iron-cli/blob/master/lib/commands/run.js#L34

and then it's being grabbed from the command line again via process.argv and appended to the end of the command

https://github.com/iron-meteor/iron-cli/blob/master/lib/commands/run.js#L40

If we're grabbing the extra args and correctly appending them to our command string, should this fix it without breaking anything?

Change https://github.com/iron-meteor/iron-cli/blob/master/lib/commands/run.js#L34
`    args = args.concat([`
`      '--settings',`
`      settingsPath`
`    ]);`
to
`    args = [`
`      '--settings',`
`      settingsPath`
`    ];`

**Comment by assutech** [comment]
So when I run "iron add-platform android" in my project directory its stuck forever at the terms and conditions and nothing happens when I enter "y". Any ideas as to how I could fix this or what I'm doing wrong. Thanks in advance.
