### ISSUE TITLE
iron debug command doesn't pass along the settings.json file

### ISSUE THREAD

**Issue by josephdburdick** [iron-meteor/iron-cli#144]
Hi @cmather , I noticed that `iron debug` passes debug to meteor but doesn't pass along the important settings.json file. I've created a pull request that solves this issue here: https://github.com/iron-meteor/iron-cli/pull/143 

In the meantime I'm developing with an alias in my .zshrc file that pulls in the file but I have to in the /app directory.

**Comment by cmather** [comment]
Sweet thanks will take a look

**Comment by josephdburdick** [comment]
@cmather Is there anything about this PR that you want changed? I realize it's now 2 features combined.

**Comment by josephdburdick** [comment]
I am closing this as #143 has been merged and I've experienced positive results testing it on my own machine.
