### ISSUE TITLE
Name confusing

### ISSUE THREAD

**Issue by repjackson** [iron-meteor/iron-cli#147]
I find the name confusing.  Iron command line interface what?  And it's tough to say cli.  If you called it the iron command line interface tool (iron clit) it would be more informative and easier to say.

**Comment by josephdburdick** [comment]
LOL, seriously? :trollface:

**Comment by dannyk08** [comment]
Well I'm sure this suggestion will leave many of us really excited

**Comment by scottmcpherson** [comment]
Ha, sorry @repjackson, I don't that name change is going to happen :)
