### ISSUE TITLE
Iron meteor won't install with -g

### ISSUE THREAD

**Issue by skolade** [iron-meteor/iron-cli#148]
I was tring to istall iron-cli, but I am getting an error on 

npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js 
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

But it will install without passing the global option!

**Comment by blevinscm** [comment]
I also have had the same issue.

**Comment by jasonbahl** [comment]
I'm also not able to install with `npm install iron-meteor` or `npm install -g iron-meteor` on Mac OS X (10.10.3)

**Comment by BurningDog** [comment]
Last week I had the same problem (on OS X 10.9.5) but today ```npm install -g iron-meteor``` worked. Is everyone else still having the same problem?

**Comment by skolade** [comment]
@BurningDog I am using OS X 10.9.5 with iojs.org node version 2.3.0, and npm 2.11.1 but still not working! thanks for sharing your success though!

**Comment by blevinscm** [comment]
I was able to get it to work with sudo today.  Not sure why it works for me now on OS x 10.10.13

**Comment by Shaunakde** [comment]
I am on windows. The -g flag is not working:
```
C:\Users\shaunakDe>npm install -g iron-meteor
/


> fibers@1.0.5 install C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
-
C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (rebuild --release )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  fibers.cc
  coroutine.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception h andler used, but unwind semantics are not enabled. Specify /EHsc (..\src\fibers.cc) [C:\Users\shaunakDe\App Data\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(703): warning C4244: 'argument' : conversion from 'size_t' to 'double', possible loss of d ata [C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxpr oj]
..\src\fibers.cc(707): warning C4244: '=' : conversion from 'double' to 'size_t', possible loss of data [C: \Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxproj]
..\src\fibers.cc(714): warning C4244: 'argument' : conversion from 'size_t' to 'double', possible loss of d ata [C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxpr oj]
..\src\coroutine.cc(109): warning C4552: '!' : operator has no effect; expected operator with side-effect [ C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxproj]
..\src\coroutine.cc(185): warning C4267: 'argument' : conversion from 'size_t' to 'unsigned int', possible
loss of data [C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fib ers.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(694): warning C4530: C++ exception ha ndler used, but unwind semantics are not enabled. Specify /EHsc (..\src\coroutine.cc) [C:\Users\shaunakDe\A ppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers\build\fibers.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\vector(688) : while compiling clas
  s template member function 'std::vector<void *,std::allocator<_Ty>>::vector(unsigned __int64)'
          with
          [
              _Ty=void *
          ]
          ..\src\coroutine.cc(156) : see reference to function template instantiation 'std::vector<void *,s
  td::allocator<_Ty>>::vector(unsigned __int64)' being compiled
          with
          [
              _Ty=void *
          ]
          c:\users\shaunakde\appdata\roaming\npm\node_modules\iron-meteor\node_modules\fibers\src\coroutine
  .h(16) : see reference to class template instantiation 'std::vector<void *,std::allocator<_Ty>>' being co
  mpiled
          with
          [
              _Ty=void *
          ]
  coro.c
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\shaunakDe\AppData\Roaming\npm\node_mod ules\iron-meteor\node_modules\fibers\build\fibers.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\shaunakDe\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "iron-meteor"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\shaunakDe\npm-debug.log
```

**Comment by michaelschufi** [comment]
I have the same problem like @skolade
But it's not only the -g flag.

**Comment by mediatainment** [comment]
same here

**Comment by joaroblesutn** [comment]
same here with OS X 10.10.4

**Comment by skolade** [comment]
Hoping that there will be a resolution to this soon.

**Comment by ProgHog231** [comment]
Same issues on Ubuntu 14.04. No install with either with or without -g, sudo or normal user.

**Comment by safhac** [comment]
Hey,
win7 -g || !-g  is most likly node@0.12.0 issue one needs to rollback to 0.10?

**Comment by chrisbutler** [comment]
@skolade @ProgHog231 @safhac this should be fixed with 1.2.2. can you guys let me know if you have success?

**Comment by psundar** [comment]
sudo works for me too.

**Comment by aungyin** [comment]
doesn't work for me, here is the log
------------------------------------------------------------------
aungyin@aungyin:~/workplace/meteor$ sudo npm install -g iron-meteor
npm http GET https://registry.npmjs.org/iron-meteor
npm http 304 https://registry.npmjs.org/iron-meteor
npm http GET https://registry.npmjs.org/cli-color/0.2.3
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/underscore/1.8.3
npm http GET https://registry.npmjs.org/cli-table/0.3.0
npm http GET https://registry.npmjs.org/ejs/0.8.5
npm http GET https://registry.npmjs.org/fibers/1.0.6
npm http GET https://registry.npmjs.org/single-line-log/0.4.1
npm http GET https://registry.npmjs.org/shell-source/1.0.1
npm http GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/underscore/1.8.3
npm http 304 https://registry.npmjs.org/cli-table/0.3.0
npm http 304 https://registry.npmjs.org/single-line-log/0.4.1
npm http 304 https://registry.npmjs.org/shell-source/1.0.1
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/cli-color/0.2.3
npm http 304 https://registry.npmjs.org/fibers/1.0.6
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/ejs/0.8.5
npm http GET https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/colors/0.6.2
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/concat-stream
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/colors/0.6.2
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/isarray/0.0.1

> fibers@1.0.6 install /usr/local/lib/node_modules/iron-meteor/node_modules/fibers
> node build.js || nodejs build.js

sh: 1: node: not found
`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
/usr/local/bin/iron -> /usr/local/lib/node_modules/iron-meteor/bin/iron
iron-meteor@1.2.2 /usr/local/lib/node_modules/iron-meteor
├── single-line-log@0.4.1
├── xtend@4.0.0
├── minimist@0.0.8
├── underscore@1.8.3
├── ejs@0.8.5
├── cli-table@0.3.0 (colors@0.6.2)
├── shell-source@1.0.1 (concat-stream@1.5.0)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
└── fibers@1.0.6
aungyin@aungyin:~/workplace/meteor$ iron migrate
/usr/bin/env: node: No such file or directory
aungyin@aungyin:~/workplace/meteor$ iron help
/usr/bin/env: node: No such file or directory
------------------------------------------------------------------
is something wrong with npm or other causes, pls help

**Comment by aungyin** [comment]
solved problem!!

Git is needed in my ubuntu env. In case other may have the same problem.

**Comment by changcw83** [comment]
sudo apt-get install nodejs-legacy

**Comment by aungyin** [comment]
@changcw83  
Thankz!! your command save me (like)
