### ISSUE TITLE
Online-Help on commands needed

### ISSUE THREAD

**Issue by NTTAKR** [iron-meteor/iron-cli#151]
Hi! Great tool you got there! 

But please do all users a favor and implement some help for the individual commands. 
If I want to know which arguments a iron create command has, I have found no option using help, iron help create, iron create --? or things like that. 

An even better approach would be the way yeoman does it: 

If you do not give arguments as parameters, the program asks for them giving a default value you can just accept by pressing enter. Have a look at the commandline flow, it's really well done. 

Best regards, 
  Andreas

**Comment by chrisbutler** [comment]
iron help and inline guides are present for all the commands
