### ISSUE TITLE
Authentication does not work on heroku deployment

### ISSUE THREAD

**Issue by jasonshark** [iron-meteor/iron-cli#153]
I am trying to deploy an iron app to heroku. Everything works in development, and I deployed like this:

    $ heroku login
    $ heroku git:remote -a <name-of-heroku-app>
    $ heroku config:set BUILDPACK_URL=https://github.com/lirbank/meteor-buildpack-horse.git
    $ heroku config:set ROOT_URL=https://<name-of-heroku-app>.herokuapp.com
    $ git push heroku master
    $ heroku open

The app deploys to heroku but I cannot login. I added the redirect URL: https://js-meteor-todos.herokuapp.com/_oauth/meteor-developer add added a `env.sh` file in `config/production` with my app keys. When I try to log in though the meteor developer box opens with an error:

![screen shot 2015-05-29 at 2 02 38 pm](https://cloud.githubusercontent.com/assets/3578908/7893166/e49c2ee0-060f-11e5-8a2b-1fdf678fe3e1.png)

How do I deploy an iron app to heroku with authentication enabled?

**Comment by derekclair** [comment]
I was able to deploy to Heroku using their web Dashboard. Putting my config variables in Settings and specifying and Deploying from a GitHub branch on the Deploy tab. I (foolishly) started beta-testing OS X El Capitan which isn't currently compatible with the heroku-toolbelt. Though I eventually found ```$ brew install heroku-toolbelt``` did get it installed (if anyone else made the same foolish mistake). Hope that helps.
