### ISSUE TITLE
Add support for Babel

### ISSUE THREAD

**Issue by nickytonline** [iron-meteor/iron-cli#155]
It would be great to have Babel as a JS engine. I've created pull request #154, that would allow users to create Meteor applications via the iron-cli using Babel.

You can test it in my fork by running ```iron create someApp --js es6```

**Comment by nickytonline** [comment]
Thanks for merging @scottmcpherson .

**Comment by scottmcpherson** [comment]
No problem @nickytonline. Thanks for the PR.
