### ISSUE TITLE
update Template functions

### ISSUE THREAD

**Issue by jpmolinamatute** [iron-meteor/iron-cli#156]
Hi! 
great package! it's very useful. I just noticed that this package still using old convention
for example:
    Template.Home.created = function () {
    };

    Template.Home.rendered = function () {
    };

    Template.Home.destroyed = function () {
    }; 

would it be possible to update them to:

    Template.Home.onCreated(function () {
    });

    Template.Home.onRendered(function () {
    });

    Template.Home.onDestroyed(function () {
    });

**Comment by bitIO** [comment]
It looks like the code is already there for the [javascript version](https://github.com/iron-meteor/iron-cli/blob/master/lib/templates/template/template.js), [ES6 version](https://github.com/iron-meteor/iron-cli/blob/master/lib/templates/template/template.js.es) but *not for the coffee one*.

**Comment by jpmolinamatute** [comment]
the code is there but it's not working as expected (at least for me) I created a new view and I got the old syntax. This file "app/client/templates/home/home.js" (created when you run `iron create`) has also the old syntax :-(
