### ISSUE TITLE
iron create projectname stops creating at Creating project  app... /

### ISSUE THREAD

**Issue by RWNTrading** [iron-meteor/iron-cli#158]
Not created a new project through iron-cli for a while.  Came back today and here is what I get.  When it reaches Creating project app .../ it just sits there spinning forever. 

I've tried running sudo npm install -g iron-meteor again, not sure how else to get latest version.

Anyone got any ideas??

Davids-Air:development Dave$ iron create projectname
created projectname
created projectname/.iron
created projectname/.iron/config.json
created projectname/bin
created projectname/bin/.gitkeep
created projectname/build
created projectname/build/.gitkeep
created projectname/build/README
created projectname/config
created projectname/config/.gitkeep
created projectname/config/development
created projectname/config/development/env.sh
created projectname/config/development/settings.json
Creating project  app... /

**Comment by eposschweiz** [comment]
Have the same problem. But after this i get an error:

Error creating file ... Error: EISDIR, illegal operation on a directory

**Comment by eposschweiz** [comment]
iron-meteor@1.1.2 /Users/lukasgrueter/.node/lib/node_modules/iron-meteor
├── single-line-log@0.4.1
├── xtend@4.0.0
├── minimist@0.0.8
├── ejs@0.8.5
├── underscore@1.3.3
├── cli-table@0.3.0 (colors@0.6.2)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
├── shell-source@1.0.1 (concat-stream@1.5.0)
└── fibers@1.0.5

**Comment by eposschweiz** [comment]
created ttc
created ttc/.iron
created ttc/.iron/config.json
created ttc/bin
created ttc/bin/.gitkeep
created ttc/build
created ttc/build/.gitkeep
created ttc/build/README
created ttc/config
created ttc/config/.gitkeep
created ttc/config/development
created ttc/config/development/env.sh
created ttc/config/development/settings.json
Creating project  app... |
Meteor app created
created ttc/app/client
created ttc/app/client/.gitkeep
created ttc/app/client/collections
created ttc/app/client/collections/.gitkeep
created ttc/app/client/head.html
created ttc/app/client/lib
created ttc/app/client/lib/.gitkeep
created ttc/app/client/stylesheets
created ttc/app/client/stylesheets/.gitkeep
created ttc/app/client/templates
created ttc/app/client/templates/.gitkeep
created ttc/app/client/templates/layouts
created ttc/app/client/templates/layouts/master_layout
created ttc/app/client/templates/layouts/master_layout/master_layout.html
created ttc/app/client/templates/layouts/master_layout/master_layout.js
created ttc/app/client/templates/shared
created ttc/app/client/templates/shared/loading
created ttc/app/client/templates/shared/loading/loading.html
created ttc/app/client/templates/shared/not_found
created ttc/app/client/templates/shared/not_found/not_found.html
created ttc/app/lib
created ttc/app/lib/.gitkeep
created ttc/app/lib/collections
created ttc/app/lib/collections/.gitkeep
created ttc/app/lib/controllers
created ttc/app/lib/controllers/.gitkeep
created ttc/app/lib/controllers/home_controller.js
created ttc/app/lib/methods.js
created ttc/app/lib/routes.js
created ttc/app/packages
created ttc/app/packages/.gitkeep
created ttc/app/private
created ttc/app/private/.gitkeep
created ttc/app/public
created ttc/app/public/.gitkeep
created ttc/app/server
created ttc/app/server/.gitkeep
created ttc/app/server/bootstrap.js
created ttc/app/server/collections
created ttc/app/server/collections/.gitkeep
created ttc/app/server/controllers
created ttc/app/server/controllers/.gitkeep
created ttc/app/server/lib
created ttc/app/server/lib/.gitkeep
created ttc/app/server/methods.js
created ttc/app/server/publish.js
created app/client/templates/home
created app/client/templates/home/home.html
Error creating file ... Error: EISDIR, illegal operation on a directory '/Users/lukasgrueter/Dropbox/meteorjs'
/Users/lukasgrueter/.node/lib/node_modules/iron-meteor/node_modules/fibers/future.js:245
						throw(ex);

**Comment by RWNTrading** [comment]
How is this the same problem, the issue I describe stops while creating the app, yours continues to another error related to the fibers version. I believe you can install an earlier version of node to resolve this, I might be wrong, I usually am :-)

**Comment by eposschweiz** [comment]
Sorry. But i am not a developer, i am a ceo of a company. i try to learn javascript and meteor and bring it up and running. i am not that eoloquent as a developer. I am learning. I uninstalled fibers globally and installed earlier versions. But still get the same error

**Comment by RWNTrading** [comment]
eposschweiz: I suggest you open another issue.  

The issue of "iron create <project>" just spinning appears to be linked to a slow/problematic internet connection.  I left it running and an hour later it had finished.  I tried it on another internet connection and it worked fine. Not sure why its talking online, thought it was a command-line app.

**Comment by chrisbutler** [comment]
hi @RWNTrading, can you tell me which version of iron you're running? ````iron version````

**Comment by eposschweiz** [comment]
Hi


I found it out, where the issue come from on github and wrote it on github:

https://github.com/iron-meteor/iron-cli/issues/159





—
EPOS Schweiz AG
www.epos-schweiz.ch


Local Crew in 
Zürich – Bern – Basel - Luzern


Info@epos-schweiz.ch
0041  44 222 00 44


Russikerstrasse 71
8320 Fehraltorf


Personal- & Eventsupport, 
Schlagkräftig, Schnell & Flexibel

**Comment by chrisbutler** [comment]
@eposschweiz thanks, that's not too surprising. trying to develop anything that builds at runtime is not going to work out too well with dropbox

**Comment by chrisbutler** [comment]
@RWNTrading it needs to install packages during the app creation process, which involves running ````meteor add```` which requires an internet connection

maybe we can modify it so that it simply adds the package names to the file, and they aren't downloaded/installed until first run

**Comment by eposschweiz** [comment]
Sounds like a good Idea to me. Could work.&nbsp;But it &nbsp;should do so also on scaffolding views or anything else.@RWNTrading it needs to install packages during the app creation process, which involves running meteor add which requires an internet connection

maybe we can modify it so that it simply adds the package names to the file, and they aren't downloaded/installed until first run
