### ISSUE TITLE
Additional routes file being generated

### ISSUE THREAD

**Issue by camstuart** [iron-meteor/iron-cli#162]
After creating a project with the `--js=coffee` flag, generating a new route creates an additional file with an usual file extension:

```
iron g:route '/insert_customer'
created app/lib/routes.js.coffee
```

Perhaps the js extension is not being substituted for coffee?

**Comment by chrisbutler** [comment]
hi @camstuart, can you tell me which version you are on? with a fresh project on 1.2 i don't see this happening
