### ISSUE TITLE
is this still being maintained?

### ISSUE THREAD

**Issue by chrisbutler** [iron-meteor/iron-cli#165]
there are a lot of PRs just sitting, and a lot of open issues. i'd love to actively help out @cmather

**Comment by Falieson** [comment]
I've seen different issues be discussed over the last few weeks but I've also heard that iron-router itself hasn't been maintained in a while and some people say that the future is flow-router.

**Comment by cmather** [comment]
I can add you when I get to a computer

**Comment by chrisbutler** [comment]
@cmather that would be awesome

**Comment by chrisbutler** [comment]
@cmather thank you. looking forward to giving back to a tool i've come to depend on

**Comment by cmather** [comment]
sweet, could use the help :)

**Comment by Falieson** [comment]
glad to hear there will be more contributors, iron-cli cemented meteor as my stack of choice.
