### ISSUE TITLE
updating NPM package

### ISSUE THREAD

**Issue by chrisbutler** [iron-meteor/iron-cli#168]
hey @cmather, i'd love to be able to update the version on NPM without needing to bug you. is that possible?

**Comment by chrisbutler** [comment]
@scottmcpherson do you have access to do this?

**Comment by scottmcpherson** [comment]
No, unfortunately I lost access when it was renamed to iron. Any way you can add us on to NPM @cmather ?

**Comment by cmather** [comment]
Oh sorry guys! There's a password. Email me: chris@eventedmind.com

**Comment by chrisbutler** [comment]
done!
