### ISSUE TITLE
Upgrading iron-cli to 1.2 requires manual edit to /.iron/config.json

### ISSUE THREAD

**Issue by dkoo761** [iron-meteor/iron-cli#179]
After upgrading iron-cli to version 1.2, the following commands:

`iron g:route tester`
`iron g:controller tester`

produced this error for an existing iron-cli project:

`TypeError: Cannot read property 'comments' of undefined`

Eventually I figured out that I had to manually edit /.iron/config.json for my project to add this:

```
  "generator": {
    "comments": "true"
  }
```

Hopefully this helps anyone else who runs into the same situation. Would be nice if the update to config.json it was handled automagically somehow.

**Comment by chrisbutler** [comment]
@dkoo761 thanks for pointing that out. this is definitely something that needs to be handled better overall

in the short-term, can you see if the commit above fixes the issue?

    sudo npm install -g https://github.com/chrisbutler/iron-cli/tarball/153c9f6949c12277437934d1195da4472991ed8c

**Comment by dkoo761** [comment]
Yes, that fixed it. Thanks for the speedy reply

**Comment by chrisbutler** [comment]
cool. this will go in 1.2.1, heh
