### ISSUE TITLE
what does the [--action "show"]?

### ISSUE THREAD

**Issue by spyhole** [iron-meteor/iron-cli#202]
iron g:route todos/show_todo --action "show"

when we do it ,we get the following, but what more about the "show" action?
Router.route('todos/show_todo', {
  name: 'todosShowTodo',
  controller: 'ShowTodoController',
  where: 'client',
  action: 'show'
});

**Comment by chrisbutler** [comment]
in the ```ShowTodoController``` you can add

    show: function() {}

and that will be called for the action step of the router. does that make sense?

**Comment by spyhole** [comment]
iron g:route todos/show_todo --action "show"

it's a example Generators of the iron-cli guide. here https://github.com/iron-meteor/iron-cli

**Comment by chrisbutler** [comment]
@spyhole what's the issue?
