### ISSUE TITLE
Missing Dependency: fibers:1.0.6

### ISSUE THREAD

**Issue by tomshorrock** [iron-meteor/iron-cli#207]
Hi guys, fibers:1.0.6 does not exist! Please update to 1.0.7

Cheers,
Tom

**Comment by kynan** [comment]
See laverdet/node-fibers#244

**Comment by kynan** [comment]
Fix in pr #208

**Comment by phxigloo** [comment]
Just tried an install sudo npm install -g iron-meteor

Got the fibers error
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)

The json package still showing fibers 1.06

**Comment by cmather** [comment]
It looks we just need to put out a new release to get the latest version. I would do it but I'm afraid I'm a little behind what's been done recently so want to double check wtih @chrisbutler. It looks like we just need to merge pr #208 and push a release.

Btw if anyone is held up and wants to just use a local copy:

1. clone this repository to a local folder
2. make the change you see in pr #208 
3. run npm install
4. run npm link (this will create a global command linked to the development folder). This is really useful for development too!

**Comment by Redbad72** [comment]
@cmather above workaround worked like a breeze. thnx.

**Comment by sreeraghuparuchuri** [comment]
@cmather  the workaround helped me till the installation of iron cli. 

But when i try to create a new project using iron it fails while installing iron router. Any idea when we can expect an official release?

**Comment by cmather** [comment]
I just published a new release. Let me know if anyone is still having the issue.

**Comment by sreeraghuparuchuri** [comment]
@cmather  Thanks for the release. Works fine now!

**Comment by kynan** [comment]
@cmather Thanks. Any reason for not accepting the pr?

**Comment by cmather** [comment]
Oops I should have merged the PR but just made the one line change instead. But I appreciated it!
