### ISSUE TITLE
update for meteor 1.2.0.2 and nodejs 4.1.1

### ISSUE THREAD

**Issue by spyhole** [iron-meteor/iron-cli#210]
meteor v1.2.0.2 released. nodejs v4.1.1 released. pls update iron-cli for them. thx
and add File Structure for Special Directories for meteor 1.2.0.2
for example:
client/compatibility
test

**Comment by RiaanOos** [comment]
Could this be the reason for my issue #211 ?
I have both the latest versions of Meteor and Node installed on my machine

**Comment by spyhole** [comment]
iron-cli now cannot work with nodejs v4.1.0

**Comment by RiaanOos** [comment]
I see. Thanks for that.
What version of nodejs should I install, v4.0.0, or an earlier one?

**Comment by paulgrever** [comment]
@spyhole is iron-cli not compatible with nodejs v4.1.0 on mac too? I am having issues running it.

**Comment by j20** [comment]
@paulgrever I also recently updated to Node v4.1. Uninstalling old versions of Node wiped out my global npm packages. Try reinstalling iron: `npm install -g iron-cli`.  I have Meteor 1.2.0.1 working on OS X and `iron` started my app after I reinstalled it.

**Comment by chrisbutler** [comment]
@spyhole so does meteor support node 4?

**Comment by spyhole** [comment]
@chrisbutler to see this :8ball: , https://github.com/meteor/meteor/issues/5283

**Comment by chrisbutler** [comment]
meteor doesn't support node > 0.12, and so neither does iron
