### ISSUE TITLE
Error installing iron-meteor on Windows 7 - following along on EventedMind

### ISSUE THREAD

**Issue by RiaanOos** [iron-meteor/iron-cli#211]
Hi folks,

I just cannot get iron-meteor to install on my Windows 7 machine. . 

I have installed Python 2.7
I have installed Visual Studio Express 2012 (I had some warnings here, but it was fixed after I applied the update KB2781514)

The latest errors seem to be A LOT of C++ compilation errors when I run the command npm install -g iron-meteor and after these syntax/compilation errors I see the following:

gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--rel
ease"
gyp ERR! cwd C:\Users\Riaan Oosthuizen\AppData\Roaming\npm\node_modules\iron-met
eor\node_modules\fibers
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "iron-meteor"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.7 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.7 install script 'node build.js || nodejs buil
d.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

The issue seems to start when coroutine.cc is being run - that's when all the C++ compilation / syntax errors start appearing. 

Is there no way to install iron-meteor without having to go the npm route?
I will greatly appreciate any help I can get.

**Comment by RiaanOos** [comment]
The issue I was having was due to having the latest version of nodejs installed on my machine, which is not supported by iron-meteor at this stage as stated in issue #210 
I downgraded to version v0.12.7 for nodejs and the install when through perfectly!

**Comment by raghavendraraksan** [comment]
I downgraded NodeJS to v0.12.7 in my Windows 8.1 System, but still its sowing errors.
