### ISSUE TITLE
Deployment to meteor servers 

### ISSUE THREAD

**Issue by samnajian** [iron-meteor/iron-cli#225]
I’m trying to deploy my app to meteor servers using “iron deploy {projectname}” but it asks for my email with “To instantly deploy your app to a free testing server, just enter your email address!” and then i enter my email address without any result or change and i’m stuck at this stage, any thing i should do?

**Comment by chrisbutler** [comment]
hey @samnajian, iron cli currently has an issue proxying the meteor interactive shell. the way to get around this is to first log in to meteor (`meteor login`) which will give you the same prompts but should accept your input

once you're logged in to meteor, `iron deploy` should work

**Comment by samnajian** [comment]
Thanks @chrisbutler works great now!
