### ISSUE TITLE
When build fails, there is no way to check the command success or not

### ISSUE THREAD

**Issue by veeramarni** [iron-meteor/iron-cli#227]
Right now, if the build fails due to some issue it doesn't `exit` with other than `0` and thus shell variable `$?` is always `0`.

If i want to script the build tasks, i cannot determine whether the build failed or not. 

For example i want to test this way

```
iron build --server=$ROOT_URL --architecture=os.linux.x86_64
if [ $? -ne 0 ]; then
exit 1
fi
```

**Comment by chrisbutler** [comment]
@veeramarni this is fixed in 1.7.0 !
