### ISSUE TITLE
I know what the others are for but what are we supposed to put in the bin/ directory?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [iron-meteor/iron-cli#228]
These days I'm making my first two apps using iron-cli and iron-router. I think your tools are awesome and should be integrated in Meteor. The organisation done by iron-cli is really smart, for example I like that there's both an isomorphic and a server-side methods.js

1. Anyway... I know what the others are for but what are we supposed to put in the /bin directory?
2. Also... I don't find where the class .main from /client/stylesheets/main.css is used; I'm just putting styles common to all templates in that file, including LAYOUTS. Seeing that there's no 'master_layout.css', this is what you intended right?
3. Why didn't you add comments and the events from below in master_layout (like in home.js or the files created by the iron-cli generator)? Is it a bad coding practice if we use them there as well?
```
Template.MasterLayout.onCreated(function () {
});

Template.MasterLayout.onRendered(function () {
});

Template.MasterLayout.onDestroyed(function () {
});
```

**Comment by chrisbutler** [comment]
@Laurentiu-Andronache the `bin` folder is a place to keep files related to your app, that you don't want to be included in the bundle when you deploy. you can really put anything there (i generally have `.pem` files and ssl certs, etc)

it's not necessarily bad practice to define helpers or events on the layouts, but usually there's a more appropriate place for them
