### ISSUE TITLE
fibers is failing on Windows

### ISSUE THREAD

**Issue by derekmacrae** [iron-meteor/iron-cli#229]
Was getting the following:

C:\Users\derek.macrae>npm install -g iron-meteor
C:\Users\derek.macrae\AppData\Roaming\npm\iron -> C:\Users\derek.macrae\AppData\
Roaming\npm\node_modules\iron-meteor\bin\iron

> fibers@1.0.7 install C:\Users\derek.macrae\AppData\Roaming\npm\node_modules\ir
on-meteor\node_modules\fibers
> node build.js || nodejs build.js

C:\Users\derek.macrae\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\
fibers>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_mo
dules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
 --release )  else (node  rebuild --release )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\derek.macrae\AppData\Roaming\npm\node_modules\iron-meteor\node_modules
\fibers\build\fibers.vcxproj(20,3): error MSB4019: The imported project "C:\Mic
rosoft.Cpp.Default.props" was not found. Confirm that the path in the <Import>
declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--rel
ease"
gyp ERR! cwd C:\Users\derek.macrae\AppData\Roaming\npm\node_modules\iron-meteor\
node_modules\fibers
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN install:fibers@1.0.7 fibers@1.0.7 install: `node build.js || nodejs bui
ld.js`
npm WARN install:fibers@1.0.7 Exit status 1
 

I changed the package.json to use fibers version 1.0.8 and it worked fine.

**Comment by chrisbutler** [comment]
@derekmacrae version 1.5.2 is up on NPM now, which fixes this. thanks!

**Comment by derekmacrae** [comment]
OK, thanks. Installed and created new project correctly, will test through this week to check all OK but thanks for the quick response,

Derek

Sent from my iPhone

On 27 Jan 2016, at 02:42, Chris Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekmacrae<https://github.com/derekmacrae> version 1.5.2 is up on NPM now, which fixes this. thanks!

-
Reply to this email directly or view it on GitHub<https://github.com/iron-meteor/iron-cli/issues/229#issuecomment-175355431>.


________________________________
P Please consider the environment before printing this email

The information in this email is confidential, protected by law and may be legally privileged. Only access by the addressee is authorised. If you are not the intended recipient, you must not read, use, store, copy or disseminate the information; any use of the information may be unlawful. If you have received this email in error, please notify us and destroy it immediately. Copyright in this email (and any attachments created by Impellam Group plc or any member of the Impellam Group<http://www.impellam.com/Pages/legal-notice.aspx>) belongs to Impellam Group plc. It is your responsibility to protect your system from viruses and any other harmful code or device. We try to eliminate them from emails and attachments but we accept no liability for any which remain. We may monitor or access any or all emails sent to us. Any liability (in negligence, contract or otherwise) arising from any third party taking any action, or refraining from taking any action on the basis of any of the information contained in this email is hereby excluded. The information contained in this email is not intended to be, nor should it be construed as, a direct or indirect invitation or inducement to any person to engage in investment activity. Impellam Group plc does not accept service of proceedings by email Any views expressed in this email are those of the sender and are not necessarily those of Impellam Group plc.

On the basis that you are the intended recipient, the receipt by you of this email represents your confirmation that you agree, or continue to agree to be bound by our Conditions of Business applicable to any transaction to which this email relates. If you require a copy (or a replacement copy) of the applicable Conditions of Business, please email a request by return.

Impellam Group plc is registered in England, registration number 06511961.

Registered office:  800 The Boulevard, Capability Green, Luton, Bedfordshire LU1 3BA

**Comment by derekmacrae** [comment]
Create command works but then get the following when I run the meteor command on the project:

=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20160127-09:49:31.440(0)? (STDERR)
W20160127-09:49:31.440(0)? (STDERR) C:\Users\derek.macrae\WebstormProjects\node_
modules\fibers\fibers.js:16
W20160127-09:49:31.440(0)? (STDERR)     throw new Error('`'+ modPath+ '.node` is
missing. Try reinstalling `node-fibe
W20160127-09:49:31.440(0)? (STDERR)           ^
W20160127-09:49:31.440(0)? (STDERR) Error: `C:\Users\derek.macrae\WebstormProjec
ts\node_modules\fibers\bin\win32-ia32-v8-3.14\fibers.node` is missing. Try reins
talling `node-fibers`?
W20160127-09:49:31.440(0)? (STDERR)     at Object.<anonymous> (C:\Users\derek.ma
crae\WebstormProjects\node_modules\fibers\fibers.js:16:8)
W20160127-09:49:31.440(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160127-09:49:31.440(0)? (STDERR)     at Object.Module._extensions..js (module
.js:474:10)
W20160127-09:49:31.440(0)? (STDERR)     at Module.load (module.js:356:32)
W20160127-09:49:31.440(0)? (STDERR)     at Function.Module._load (module.js:312:
12)
W20160127-09:49:31.440(0)? (STDERR)     at Module.require (module.js:364:17)
W20160127-09:49:31.440(0)? (STDERR)     at require (module.js:380:17)
W20160127-09:49:31.440(0)? (STDERR)     at Object.<anonymous> (C:\Users\derek.ma
crae\WebstormProjects\way2work2\app\.meteor\local\build\programs\server\boot.js:
1:75)
W20160127-09:49:31.440(0)? (STDERR)     at Module._compile (module.js:456:26)
W20160127-09:49:31.440(0)? (STDERR)     at Object.Module._extensions..js (module
.js:474:10)
