### ISSUE TITLE
Can't install caused by fibers

### ISSUE THREAD

**Issue by charpeni** [iron-meteor/iron-cli#238]
I tried to install the latest release (1.5.2), but it fail on Ubuntu 14.04.3 LTS.

I downgraded to 1.5.0 and it works well.

```
 ~npm install -g iron-meteor

> fibers@1.0.8 install /home/nicolas/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers
> node build.js || nodejs build.js

make: entrant dans le répertoire « /home/nicolas/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers/build »
  CXX(target) Release/obj.target/fibers/src/fibers.o
make: g++: commande introuvable
make: *** [Release/obj.target/fibers/src/fibers.o] Erreur 127
make: quittant le répertoire « /home/nicolas/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/nicolas/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.19.0-43-generic
gyp ERR! command "node" "/home/nicolas/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/nicolas/.nvm/v0.10.40/lib/node_modules/iron-meteor/node_modules/fibers
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
Build failed
sh: 1: nodejs: not found
npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the fibers@1.0.8 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-43-generic
npm ERR! command "/home/nicolas/.nvm/v0.10.40/bin/node" "/home/nicolas/.nvm/v0.10.40/bin/npm" "install" "-g" "iron-meteor"
npm ERR! cwd /home/nicolas
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by BRyeGmoney** [comment]
I have this same problem with 1.5.1 and 1.5.2 on win64

`C:\Users>npm install -g iron-meteor@1.5.1
|
> fibers@1.0.8 install C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers
> node build.js || nodejs build.js


C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers>if not defined npm_config_node_gyp (node "E:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (rebuild --release )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (E:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at E:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "E:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\iron-meteor\node_modules\fibers
gyp ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "E:\\Program Files (x86)\\nodejs\\\\node.exe" "E:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "iron-meteor@1.5.1"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.8 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.8 install script 'node build.js || nodejs build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "E:\\Program Files (x86)\\nodejs\\\\node.exe" "E:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "iron-meteor@1.5.1"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1

npm ERR! Uncaught, unspecified "error" event.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\npm-debug.log`

**Comment by stivaugoin** [comment]
Same here. Works well in 1.5.0

**Comment by bryanlimy** [comment]
same problem, on MacOS 10.12.2.

**Comment by chrisbutler** [comment]
does 1.5.3 work for anyone? @charpeni @BRyeGmoney  @stivaugoin @bryanlimy

**Comment by stivaugoin** [comment]
@chrisbutler 1.5.3 works well on macOS 10.12.2

**Comment by chrisbutler** [comment]
@stivaugoin can you try updating to 1.5.4 that i just released?

**Comment by stivaugoin** [comment]
@chrisbutler it works!

**Comment by chrisbutler** [comment]
@stivaugoin cool, thanks!
