### ISSUE TITLE
Meteor 1.3 broke iron-cli

### ISSUE THREAD

**Issue by chriskgregory** [iron-meteor/iron-cli#240]
Not working. When I try to create a project it says "Error: EPERM, operation not permitted"

Edit: I've tried on Windows 7, Windows 10, and Windows 8.1 with earlier and up-to-date versions of Iron-Meteor.

**Comment by FBRTMaka** [comment]
Same problem.

**Comment by katgrigg** [comment]
I'm having the same issue.

**Comment by FBRTMaka** [comment]
Found a (hopefully very temporary) workaround:
1. Run iron create <app name>
2. After the error, cd into <app name>
3. Run iron init, and 'y/n' through all the prompts.
4. it'll finish scaffolding the app.

**Comment by FBRTMaka** [comment]
PR to fix this Meteor 1.3 bug using iron create
https://github.com/iron-meteor/iron-cli/pull/241

**Comment by chriskgregory** [comment]
Doesn't work on windows for me.

"Error: Cannot find module 'delete'

**Comment by abhinavkumar940** [comment]
@FBRTMaka 's solution works for me on Ubuntu 15.10

**Comment by FBRTMaka** [comment]
@chriskgregory , could you try installing delete globally?

**Comment by malajmovic** [comment]
Can confirm that Maka's solution also works for me on both Linux Mint 17.3 and Windows 10. Can even run meteor / iron update without breaking anything

**Comment by switheyw** [comment]
Matt's 'iron init' rerun did not work for me on OS X 10.11.4, but just rerunning 'iron create [y/n]' did.  Also, I have a fix for the problem (can't find the delete module required by PR 241) but not sure how to go about it.  The fix involves calling (gist.github.com/) [geedew's](https://gist.github.com/geedew) wonderful recursive file delete routine when a directory is encountered.

**Comment by maka-io** [comment]
@switheyw I updated the PR since @chriskgregory experienced the error, I've had it running on Windows 7 / 10 without any problems.

**Comment by chrisbutler** [comment]
should be fixed in 1.5.3
