### ISSUE TITLE
Using Collection Fs with iron cli

### ISSUE THREAD

**Issue by openqubit** [iron-meteor/iron-cli#243]
I am using collection fs package https://github.com/CollectionFS/Meteor-CollectionFS to try and upload my images.I have a collection file called schools.js and in it i have this code

```
 SchoolImages = new FS.Collection("schoolimages", {
        stores: [new FS.Store.GridFS("schoolimages")]
    });

Schools = new Mongo.Collection('schools');
```

For some reason,the schoolimages collection isn't being created. Why is this?.

**Comment by maka-io** [comment]
@openqubit check this out:
https://atmospherejs.com/cfs/gridfs

**Comment by openqubit** [comment]
It was a 403 error which i solved by adding

```
 download:function(){
    return true;
  }
```

to my collection allow list.
