### ISSUE TITLE
i cannot use iron because of fibers, how i can fix it

### ISSUE THREAD

**Issue by elidiazgt** [iron-meteor/iron-cli#252]
![screenshot 2016-11-25 13 03 13](https://cloud.githubusercontent.com/assets/11800064/20633779/abd1f8e8-b30f-11e6-8996-08ab0c79f62b.png)

**Comment by jstoup111** [comment]
I'm getting the same issue. It looks like the way it generates the `darwin-x64-v8-5.4` is wrong. My path to `darwin-x64-v8-5.6` exists but the one above does not.

I hard coded the value but still ran into issues. Running meteor 1.4 and node 4.4.7.

**Comment by chrisbutler** [comment]
@elidiazgt @jstoup111 can you guys try again with the latest version of iron-cli?
