### ISSUE TITLE
iron-cli problem with meteor 1.4.2.3 include babel-runtime

### ISSUE THREAD

**Issue by AirJordan6811** [iron-meteor/iron-cli#253]
Hi,
I have some problems with iron-cli, metor 1.4.2.3 and babel runtime. App starts and then I get error messages. 

> Error: The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:

>  meteor npm install --save babel-runtime  babel-runtime.js:47:9

meteor npm install --save babel-runtime I have made. If the error is known, someone can help? Thx.

**Comment by AirJordan6811** [comment]
Error code from the browser console:

> Error:

>  The babel-runtime npm package could not be found in your node_modules 
directory. Please run the following command to install it:
meteor npm install --save babel-runtime
  babel-runtime.js:47:9
TypeError: Package["babel-runtime"] is undefined[Weitere Informationen]  random.js:24:5
TypeError: Package.random is undefined[Weitere Informationen]  mongo-id.js:19:5
TypeError: Package["mongo-id"] is undefined[Weitere Informationen]  minimongo.js:23:5
TypeError: Package.random is undefined[Weitere Informationen]  retry.js:18:5
TypeError: Package.random is undefined[Weitere Informationen]  ddp-common.js:19:5
TypeError: Package.random is undefined[Weitere Informationen]  ddp-client.js:19:5
TypeError: Package["ddp-client"] is undefined[Weitere Informationen]  ddp.js:14:5
TypeError: Package.minimongo is undefined[Weitere Informationen]  allow-deny.js:18:5
TypeError: Package["allow-deny"] is undefined[Weitere Informationen]  mongo.js:17:5
TypeError: Package["mongo-id"] is undefined[Weitere Informationen]  observe-sequence.js:19:5
TypeError: Package["observe-sequence"] is undefined[Weitere Informationen]  blaze.js:24:5
TypeError: Package.blaze is undefined[Weitere Informationen]  ui.js:14:5
TypeError: Package["observe-sequence"] is undefined[Weitere Informationen]  spacebars.js:17:5
TypeError: Package.blaze is undefined[Weitere Informationen]  templating-runtime.js:18:5
TypeError: Package["templating-runtime"] is undefined[Weitere Informationen]  templating.js:14:5
TypeError: Package.ui is undefined[Weitere Informationen]  iron_dynamic-template.js:17:5
TypeError: Package["templating-runtime"] is undefined[Weitere Informationen]  iron_layout.js:17:5
TypeError: Package["templating-runtime"] is undefined[Weitere Informationen]  iron_controller.js:21:5
TypeError: Package.blaze is undefined[Weitere Informationen]  iron_router.js:17:5
TypeError: Package.random is undefined[Weitere Informationen]  aldeed_simple-schema.js:22:5
TypeError: Package["ddp-client"] is undefined[Weitere Informationen]  livedata.js:14:5
TypeError: Package["aldeed:simple-schema"] is undefined[Weitere Informationen]  aldeed_collection2.js:17:5
TypeError: Package["aldeed:simple-schema"] is undefined[Weitere Informationen]  aldeed_autoform.js:17:5
TypeError: Package["babel-runtime"] is undefined[Weitere Informationen]  webapp.js:24:5
TypeError: Package.retry is undefined[Weitere Informationen]  autoupdate.js:19:5
TypeError: Package.mongo is undefined[Weitere Informationen]  global-imports.js:3:1
ReferenceError: meteorInstall is not defined[Weitere Informationen]

**Comment by chrisbutler** [comment]
should be fixed in 1.5.5

there's no need to use `grigio:babel` anymore
