### ISSUE TITLE
EM installation error

### ISSUE THREAD

**Issue by rnarayan** [iron-meteor/iron-cli#26]
I am running Ubuntu 13.04. When I tried to install EM (sudo npm -g install meteor-em), I get error. Other prerequisite software are installed and I have successfully created several meteor apps on this laptop before. I get the following error in the terminal console. There is a big NPM log file too which I could email to you.

$ sudo npm -g install meteor-em
[sudo] password: 
npm http GET https://registry.npmjs.org/meteor-em
npm http 304 https://registry.npmjs.org/meteor-em
npm http GET https://registry.npmjs.org/cli-color/0.2.3
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/underscore/1.3.3
npm http GET https://registry.npmjs.org/cli-table/0.3.0
npm http GET https://registry.npmjs.org/ejs/0.8.5
npm http GET https://registry.npmjs.org/fibers/1.0.1
npm http 304 https://registry.npmjs.org/cli-color/0.2.3
npm http 304 https://registry.npmjs.org/underscore/1.3.3
npm http 304 https://registry.npmjs.org/fibers/1.0.1
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/cli-table/0.3.0
npm http 304 https://registry.npmjs.org/ejs/0.8.5
npm http GET https://registry.npmjs.org/colors/0.6.2
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/colors/0.6.2

> fibers@1.0.1 install /usr/local/lib/node_modules/meteor-em/node_modules/fibers
> node ./build.js

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:65:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:150:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:93:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:719:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:107:17)
gyp ERR! stack     at maybeClose (child_process.js:991:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1058:5)
gyp ERR! System Linux 3.8.11
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/meteor-em/node_modules/fibers
gyp ERR! node -v v0.11.13-pre
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
Build failed
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/memoizee
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/meteor-em/node_modules/cli-color/node_modules/es5-ext/test/Array/of.js'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.8.11
npm ERR! command "node" "/usr/local/bin/npm" "-g" "install" "meteor-em"
npm ERR! cwd /home/newgeek
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.4
npm ERR! path /usr/local/lib/node_modules/meteor-em/node_modules/cli-color/node_modules/es5-ext/test/Array/of.js
npm ERR! fstream_path /usr/local/lib/node_modules/meteor-em/node_modules/cli-color/node_modules/es5-ext/test/Array/of.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:97:15)
npm ERR! fibers@1.0.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@1.0.1 install script.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.8.11
npm ERR! command "node" "/usr/local/bin/npm" "-g" "install" "meteor-em"
npm ERR! cwd /home/newgeek
npm ERR! node -v v0.11.13-pre
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/next-tick
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/newgeek/npm-debug.log
npm ERR! not ok code 0

**Comment by stbain** [comment]
Note: this will fix it so you can install fibers, but it may mess things up if you install the amateur radio "node" package.

cd /usr/bin
ln -s nodejs node
