### ISSUE TITLE
Enhancement: --version flag

### ISSUE THREAD

**Issue by lirbank** [iron-meteor/iron-cli#65]
It would be nice to be able to check the em version without having to type `npm list -g|grep meteor-em`, eg:
```
$ em --version
```

**Comment by cmather** [comment]
Agreed! PR please!

**Comment by josephdburdick** [comment]
I didn't see this until now but I have a PR open to handle this.  You could use `iron version` or `iron v`. No -- necessary and it would show in the iron help prompt. Once #130 is accepted and merged you'll have this functionality.

**Comment by josephdburdick** [comment]
This can be closed as #130 was merged 2 days ago.

**Comment by chrisbutler** [comment]
thanks @josephdburdick

**Comment by lirbank** [comment]
Sweet, thanks!
