### ISSUE TITLE
Enhancement: Add deny rule to prevent user.profile writes

### ISSUE THREAD

**Issue by lirbank** [iron-meteor/iron-cli#66]
Referring to #22 to further secure default apps I think it would be great to add a collection file for the users collection, eg `server/collections/user.js` with the following scaffolding:

```javascript
Meteor.users.deny({
  update: function () {
    return true; }
  }
);
```

Developers can then remove this as the wish. I for one repeatedly add these lines to most of my projects.

The profile object of the logged in user can to be written to freely (by the logged in user itself), which I am sure there are not a lot of use cases for - so might as well turn it off so you don't have to think about it when you write the rest of the logic.

I guess some people like allow/deny and some prefer to rely solely on Meteor methods for DB manipulation. If you're the later you probably want these lines (turning of client direct writes to the DB completely). If you're the former you can simply remove this file if you like.

Having a collections file for the users collection `server/collections/user.js` is also useful for other configuration, such as ensuring indexes, eg:

```javascript
Meteor.users._ensureIndex (
  {handle: 1},
  {unique: true, sparse: true}
);
```

**Comment by ianserlin** [comment]
Adding this file to help force DB operations through methods hinders one of the most awesome aspects of Meteor. I would recommend not doing this by default.

However, I would like to see iron-meteor support customized re-usable project templates, but that's a different PR. ;) And that would save @lirbank time.
