### ISSUE TITLE
Routing doesn't work when doing 'em init' using coffeescript

### ISSUE THREAD

**Issue by afuggini** [iron-meteor/iron-cli#68]
When I create a new project from scratch using `$ em init --ir --css=false --js=coffee` and create a route, I still see Iron Router's initial page. Doesn't happen when using Javascript, though. Why could this be?

If I turn router.coffee into router.js it works just fine.

**Comment by cmather** [comment]
as mentioned the coffeescript package is not auto installed. maybe we should for the supported engines?

**Comment by cmather** [comment]
i think this should happen automatically. Anyone want to take a stab at it? Btw 1.1.0 just released a second ago.

**Comment by chrisbutler** [comment]
i have it committed [here](https://github.com/chrisbutler/iron-cli/commit/501b8fea0630b9c0d7ac40334e23e95b2b4c6471)... will merge when the rest of the generators are updated
