### ISSUE TITLE
Enhancement: Auto install dependents packages

### ISSUE THREAD

**Issue by brunolemos** [iron-meteor/iron-cli#72]
We have to do this now:

``` shell
em create test --html=jade --css=sass --js=coffee
cd test/
meteor add iron:router
meteor add fourseven:scss
meteor add mquandalle:jade
meteor add coffeescript
```

Expected:

``` shell
em create test [--config=myCustomGlobalConfig]
```

I expect it to load my global default configurations and to automatically install my predefined packages. 
Thanks.

**Comment by cmather** [comment]
how do we choose which package to do with?

**Comment by cmather** [comment]
like the idea though. confusing that these engine packages aren't installed automatically.

**Comment by chrisbutler** [comment]
this exists currently
