### ISSUE TITLE
Enhancement: Slightly documentation improvement

### ISSUE THREAD

**Issue by mediatainment** [iron-meteor/iron-cli#74]
Hi, 

At first thanks for this great Lib. It gives Noobs a Jumpstart!
I am coming from the "rails world" and have some troubles to find out, how the scaffolding tool acts with some files. So I am not sure how or what these files are doing. 

So my question is what are the following files are doing or made for?

    /both/app.js
    /client/app.js
    /scripts

Are you so kind and can give me an example how to use them (like you did in all the other files)? Or some demo code (link) where I can see this in real world apps?

I am also a customer on eventedmind.com where I go through your school and write currently a german book "Meteor for Rubyists" where your scaffolder will be a main part of it. Hope it's ok :-) 

many thanks in advance

**Comment by cmather** [comment]
Hey @mediatainment, Thanks for being a customer on EM :). For your question, I'll be posting a class shortly that uses the new iron command line tool (see the cmather branch). For real world examples, you can create the meteor examples like this:

```meteor create --example todos```
