### ISSUE TITLE
Bug: Creating server side routes has problems

### ISSUE THREAD

**Issue by lirbank** [iron-meteor/iron-cli#75]
This command:
```sh
$ em g:route myRoute --where server
```
produces the following files:
```sh
updated both/router/routes.js
created /server/controllers/my_route.js
created /client/views/my_route
created /client/views/my_route/my_route.html
created /client/views/my_route/my_route.css
created /client/views/my_route/my_route.js
```
The router update has errors and the views should not be created, as follows:

#### Router
This line is added to `both/router/routes.js`:
```javascript```
Router.route('/', {name: 'my.route'});
```
but to make the server side route working it should be like this:
```javascript```
Router.route('/', {name: my.route', where: 'server'});
```
#### Controller
The `/server/controllers/my_route.js` is ok.

#### Views
The client side views should not be created at all.

**Comment by cmather** [comment]
Check out the new commands and generators in cmather branch which I'll merge soon. The route command just adds a route, nothing else.

**Comment by lirbank** [comment]
Awesome! So now you create route and controller in two steps instead?

**Comment by cmather** [comment]
Yeah or you can use the scaffold command. Might need to adjust the generator logic a bit. Take a look at the new stuff and see if I missed any spots.

**Comment by lirbank** [comment]
Looking at it now! Just tried the new approach. I'll start another thread with my thoughts.
