### ISSUE TITLE
Discussion: creating Routes and Controllers

### ISSUE THREAD

**Issue by lirbank** [iron-meteor/iron-cli#79]
I like the simplicity of each-command-do-only-one thing. But when it comes to routes I actually think `g:route` should create both the route and the controller. 

Are there any use cases where you want to create more than one controller per route? Else we could remote the `g:controller` command all together.

**Comment by cmather** [comment]
My thinking was that you'd probably have one controller for more than one route, especially if we start using HTTP verbs. So you'd have multiple action functions. But we don't really have a concept of restful routes. But generally I don't have one route to one controller.

**Comment by cmather** [comment]
i think this is being worked on by scott
