### ISSUE TITLE
Exporting environment variables

### ISSUE THREAD

**Issue by scott-mcpherson** [iron-meteor/iron-cli#80]
I noticed when the app is ran using the iron command, the env file is "sourced".

The environment variables should be accessible from the meteor shell after the app is ran with the iron command, right?

For some reason, none of my environment variables are set when I open the meteor shell. 

I logged my envPath in [this conditional](https://github.com/iron-meteor/iron-cli/blob/master/lib/commands/run.js#L26-L27) and it looks like the file path is there, but for some reason either the env is not being executed, or my environment variables are not being exported.

Any ideas @cmather ?

**Comment by cmather** [comment]
Hmm. That's my expectation. Are they visible in your Web app? I haven't played with the Meteor shell. I wonder if they're resetting the environment on spawn (you don't have to pass the current process.env down to child processes if you don't want). But I'm passing the current environment to the meteor tool. Check out lib/tools/meteor.js L156. Is the proper env set at that point?

**Comment by scott-mcpherson** [comment]
At lib/tools/meteor.js L156 it looks like the export keys are strings instead of variables.
Check out the last two variables from this screen shot:
![screen shot 2015-02-13 at 9 33 43 pm](https://cloud.githubusercontent.com/assets/2382172/6198340/6a3547a2-b3c8-11e4-896f-a036988c00bd.png)

**Comment by scott-mcpherson** [comment]
Also, the variables are not visible in the app @cmather
