### ISSUE TITLE
Add support for different html, javascript, and css engines.

### ISSUE THREAD

**Issue by scott-mcpherson** [iron-meteor/iron-cli#81]
I'll begin working on this over the next couple of days.

Engines that need to be supported:

JavaScript
- CoffeeScript
- TypeScript

html
- Jade

css
- Less
- Sass (scss)
- Stylus
  
Note: I also need to map stylus to styl, sass to scss, typescript to ts, and coffeescript to coffee.

Please let me know if I'm missing any.

**Comment by cmather** [comment]
Sweet!

**Comment by alanpog** [comment]
Was typescript generation implemented or at least started somewhere?
