### ISSUE TITLE
'iron-meteor' is not in the npm registry

### ISSUE THREAD

**Issue by praneybehl** [iron-meteor/iron-cli#85]
While trying to install I get the error "'iron-meteor' is not in the npm registry"
I tried to find the package on NPM registry as well but no luck. Seems like it needs to be published or maybe I am missing something.

Thanks

**Comment by Morganjackson** [comment]
Same here.

**Comment by scott-mcpherson** [comment]
It looks like we haven't released iron-meteor to npm yet. It's under active development and we wanted to get a few things finished up before releasing. @Morganjackson is correct if you want to begin using it before we release.

Just a heads up though: A few things that are supported with em are not yet supported with iron @praneybehl @Morganjackson .

**Comment by Morganjackson** [comment]
@scott-mcpherson Thanks Scott. Looks great so far!

**Comment by praneybehl** [comment]
@scott-mcpherson @Morganjackson Thanks guys

**Comment by buduguru** [comment]
Installed iron cli as @Morganjackson suggested, but `iron` command was not found. 
I use elementary os 
shell output: https://gist.github.com/buduguru/f510a2ac909bf10dcb93

**Comment by cmather** [comment]
Install using `npm install -g iron-meteor`
