### ISSUE TITLE
[Bug] Template dest file is not being rewritten with engine extension

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-cli#87]

**Comment by scott-mcpherson** [comment]
It looks like the same thing is going on with the style sheet generator @cmather.

**Comment by cmather** [comment]
Okay try it out now. Hopefully fixed.

**Comment by scott-mcpherson** [comment]
It looks like it's doubling up the alternative extension when it's searching for the file:
`Error: Couldn't find a source template in "/Users/scotty/Develop/Utilities/iron/lib/templates/app/client/head.html.jade.jade"`

**Comment by cmather** [comment]
Ok I'll take another look. I didn't test the html generator.

**Comment by cmather** [comment]
Although, it was working for template.css.less.

**Comment by cmather** [comment]
Ok, hopefully this time I got it.

**Comment by cmather** [comment]
I'm also just going to merge this into master and get rid of the extra branches. Easier for people to follow and contribute. You're on the right track for adding the appropriate engine files.
