### ISSUE TITLE
[Bug] Coffeescript files are created with the content of the JavaScript templates

### ISSUE THREAD

**Issue by MasterAM** [iron-meteor/iron-cli#89]
Generated CoffeeScript files contain the source of the JavaScript templates.
 
I suspect that this also occurs with jade and html, but didn't test it.
It is reproducible via the `create` command, for example `app/client/templates/home/home.coffee/`.

It appears that `rewriteSourcePathForEngine()` does not reach the file name replacement execution path (`fileType` equals `'js'`), so the `js` template is imported.

**Comment by cmather** [comment]
Oh blasted. I'll take another look this evening or in the morning. Thanks for reporting.

**Comment by cmather** [comment]
@scott-mcpherson, @lirbank, I could use help with this issue if either of you have a chance to take a look.

**Comment by scott-mcpherson** [comment]
It looks like on line [32](https://github.com/iron-meteor/iron-cli/blob/master/lib/generators/template.js#L32) in generators/template.js, we're passing in the source path for the js template file, which gets passed to templateContent in file_system.js, but nowhere along the way are we checking the config file. 

The master_layout.js is parsing the correct coffee code. So it looks like `copyTemplateDirectory` is parsing the correct source files.

If you want, I'd be happy to throw something together @cmather ?

**Comment by cmather** [comment]
Thanks @scott-mcpherson, if you have time to take a look that would be great. But line 32 is fine. When you use the templates you pass the source path for the type of file you're looking for, regardless of engine (i.e. html, js, css). Then, the config options should automatically figure out which one to get based on the configured engine. With this bug I would start by confirming you can reproduce the behavior explained by @MasterAM above. If it turns out we're grabbing the wrong file, look in lib/tools/file_system.js and trace through:

1. pathFromTemplates
2. rewriteSourcePathForEngine

**Comment by scott-mcpherson** [comment]
My mistake. It looks we are checking the cofig file and the problem might on lines196-197: https://github.com/iron-meteor/iron-cli/blob/master/lib/tools/file_system.js#L196-L197.

If I remove that if statement, it gives the rest of that function a chance to rewrite the sourrc extension.

**Comment by scott-mcpherson** [comment]
I'm getting ready to push a commit that fixes this issues @MasterAM. I don't use CoffeeScript, and I've been just using [js to coffee](http://js2.coffee/) to convert the js to coffee. So if there's any syntax issues with the coffee, just let me know and I'll be happy to update the template files.

**Comment by MasterAM** [comment]
Cool. Seems to do the trick.
Regarding CoffeeScript, there is an issue with global/exported variables. MDG suggests using a special variable called `share`. It is available to js code globally via an object (`__coffeescriptShare`) and does not pollute the global namespace.
There are alternative methods that use the global namespace.

I will think about it some more and create a PR.

**Comment by cmather** [comment]
Hmm I wonder what my original intent was. But definitely looks like a mistake. Will double check tomorrow. Thanks for hunting it down!
