### ISSUE TITLE
Coffeescript scaffolding issue

### ISSUE THREAD

**Issue by meteorpoly** [iron-meteor/iron-cli#92]
When I specify --js=coffee while creating a new iron app it seems there is a variable scope problem. The error I get on a default application scaffold is: `Error: RouteController 'HomeController' is not defined.` The problem is that it should generate `@HomeController` instead of `HomeController` and the same goes also when scaffolding new controllers under the coffeescript configuration etc.
This problem existed also in the pre 1.0 release of the iron-meteor npm package. Is it only me getting this error or did I get something terribly wrong?
Even though I fixed the template code locally (added the @ in front of global vars), a fix would be highly appreciated if it turns out to be a small bug.

For those going with the coffee & scss config e.g.: `iron create [application name goes here] --js=coffee --css=scss ` don't forget (the obvious) to add `meteor add coffeescript` and `meteor add fourseven:scss` to you app.

**Comment by meteorpoly** [comment]
Another issue when executing: `iron g"collection todo` id **...todo.coffee:19: unmatched }**. The coffeescript code has an } (curly brace) at the end of the file throwing a compile error.

**Comment by MasterAM** [comment]
Yepp, I also noticed this (https://github.com/iron-meteor/iron-cli/issues/89#issuecomment-76126418). I'm not sure what is the best approach for sharing variables (variables that should be accessed by JS code should probably be global).

I am considering 2 approaches:

1. Using `share`

    ```coffeescript
    Router.route '/',
      name: 'home'
      controller: '__coffeescriptShare.HomeController'
      action: 'action'
      where: 'client'
    ```


  with the following controller:
  ```coffeescript
  HomeController = RouteController.extend(
    ...
  )
  
  share.HomeController = HomeController;
  ```
  
  **Pro:** namespacing
  **Con:** less elegant

2. Using the global namespace
  As you suggest:
  ```coffeescript
  @HomeController = RouteController.extend(
    ...
  )
  ```

**Comment by meteorpoly** [comment]
Another issue when executing `iron g:scaffold todo' it creates a file called publish.**js**.coffee even though there is already one called publish.coffee. The `}` issue exists of course also here since it uses the same coffee template I guess.

**Comment by meteorpoly** [comment]
@MasterAM I think the `@` approach is what Chris generally applies. In the controllers template for example he used the `@` prefix.

**Comment by cmather** [comment]
Oops will take a look

**Comment by cmather** [comment]
Hey @scott-mcpherson, when you added the coffee templates did you mean to add the `@` token in front of the controllers? Or is there another way to make them global? I don't usually write coffeescript but I seem to recall that's the correct way to assign to a global.

**Comment by cmather** [comment]
I can also confirm some roque tokens in the collection.js.coffee template.

**Comment by cmather** [comment]
Ok can someone try this on the master branch and let me know if it works as expected. To do that follow these steps:

```
> git clone https://github.com/iron-meteor/iron-cli.git iron-cli
> cd iron-cli
> npm install
> npm link
```

That will create the global npm executable from the project npm module.

**Comment by scott-mcpherson** [comment]
It's been a while since I've used coffee script but I think you're right. I just used the js to coffee web app to convert it. I can look into it when I get back home

**Comment by cmather** [comment]
I think I got it. Just need someone to try it out.

**Comment by meteorpoly** [comment]
@cmather I did some basic test's and the results are as follows:
- Collections have now the `@` token
- Controllers code is broken now, you removed the `@` token from the Controllers?
- Duplicate files are created e.g. route.js / route**.js**.coffee and publish.js / publish**.js**.coffee. Please keep only the files with **[name].coffee**

**Comment by meteorpoly** [comment]
Any news here?

**Comment by cmather** [comment]
Coming back to it later this week.

**Comment by meteorpoly** [comment]
ok thanks for the update... standing guard
