### ISSUE TITLE
Not able to run with --port argument

### ISSUE THREAD

**Issue by caioreis** [iron-meteor/iron-cli#93]
I'm not able to use --port arument when using iron run. Since I can't use PORT variable in development, this would be useful.

Tks

**Comment by MiroHibler** [comment]
Are you using equal sign to assign port? For example:

```bash
iron run --port=1337
```
It works for me like a charm.

**Comment by cmather** [comment]
this would work. closing for now but comment if you're still having problems.

**Comment by caioreis** [comment]
Just to clarify, just typing meteor --port 4000 works, different than iron --port 4000. My error was here, forgeting to use the iron run and using it like meteor.

**Comment by MiroHibler** [comment]
I assumed you tried with the `meteor` instead of `iron`, that's why I wrote the whole command ;)

Anyway, I'm glad you got it working, it's a great tool :)
