### ISSUE TITLE
Meteor n00b trying to get iron going here. Following along with Evented Mind tutorial

### ISSUE THREAD

**Issue by webdevdjm** [iron-meteor/iron-cli#98]
Getting -bash: iron: command not found when running iron at command line. Not sure if bug or something I'm doing but???
## Davids-MBP:~ name-omitted$ npm install -g iron-meteor

> fibers@1.0.1 install /Users/name-omitted/.npm-packages/lib/node_modules/iron-meteor/node_modules/fibers
> node ./build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
  SOLINK_MODULE(target) Release/fibers.node: Finished
Installed in `/Users/name-omitted/.npm-packages/lib/node_modules/iron-meteor/node_modules/fibers/bin/darwin-x64-v8-3.14/fibers.node`
/Users/name-omitted/.npm-packages/bin/iron -> /Users/davidmorse/.npm-packages/lib/node_modules/iron-meteor/bin/iron
iron-meteor@1.0.0 /Users/name-omitted/.npm-packages/lib/node_modules/iron-meteor
├── single-line-log@0.4.1
├── xtend@4.0.0
├── minimist@0.0.8
├── ejs@0.8.5
├── cli-table@0.3.0 (colors@0.6.2)
├── underscore@1.3.3
├── shell-source@1.0.1 (concat-stream@1.4.7)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
└── fibers@1.0.1
Davids-MBP:~ name-omitted$ iron
-bash: iron: command not found

**Comment by cmather** [comment]
It looks like npm installed the `iron` executable into /Users/name-omitted/.npm-packages/bin/iron. Is that path in your PATH environment variable? `echo $PATH`. You might have npm configured differently, but in my installation it also puts executables into /usr/local/bin. You could probably fix your issue by appending the install path to your PATH env like this:

```
echo 'export PATH="~/.npm-packages/bin:$PATH"' >> ~/.bashrc
```

**Comment by webdevdjm** [comment]
Fixing the path solved the problem. Thanks for your help, really appreciate it!
David

**Comment by hvtor** [comment]
Having the same issue, but following the above steps isn't really working out : 

> fibers@1.0.5 install /Users/hvt/.node/lib/node_modules/iron-meteor/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/fibers.node
  SOLINK_MODULE(target) Release/fibers.node: Finished
Installed in `/Users/hvt/.node/lib/node_modules/iron-meteor/node_modules/fibers/bin/darwin-x64-v8-3.28/fibers.node`
/Users/hvt/.node/bin/iron -> /Users/hvt/.node/lib/node_modules/iron-meteor/bin/iron
iron-meteor@1.1.1 /Users/hvt/.node/lib/node_modules/iron-meteor
├── single-line-log@0.4.1
├── xtend@4.0.0
├── minimist@0.0.8
├── ejs@0.8.5
├── underscore@1.3.3
├── cli-table@0.3.0 (colors@0.6.2)
├── shell-source@1.0.1 (concat-stream@1.4.7)
├── cli-color@0.2.3 (memoizee@0.2.6, es5-ext@0.9.2)
└── fibers@1.0.5
➜  ~  echo $PATH
/usr/local/heroku/bin:/Users/hvt/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
➜  ~  echo 'export PATH="~/.node/lib/node_modules/iron-meteor/bin/iron:$PATH"' >> ~/.bashrc
➜  ~  iron
zsh: command not found: iron

Anything I am doing wrong here?

**Comment by cmather** [comment]
what version of npm and node are you on?

**Comment by hvtor** [comment]
➜  ~  node -v
v0.12.0
➜  ~  npm -v
2.5.1

**Comment by cmather** [comment]
Not sure why npm isn't putting the executable into one of the standard install paths. I'll have to check that out. In the mean time, your script to add the npm executable path is a little off.

```bash
> echo 'export PATH="~/.node/lib/node_modules/iron-meteor/bin:$PATH"' >> ~/.bashrc
```

**Comment by hvtor** [comment]
Still not getting the iron command unfortunately.

~/.bashrc file contains:

export PATH="~/.npm-packages/bin:$PATH"
export PATH="~/.node/lib/node_modules/iron-meteor/bin:$PATH"

**Comment by therinken** [comment]
Not sure if this will help @hvtor ... but, if you're on a mac and you can't seem to get this to work... I had to change the permissions on some directories before npm would even consider installing (and, my errors looked similar to @hvtor) ... hope this helps someone...

> sudo chown -R $USER ~/.npm
> sudo chown -R $USER /usr/local/lib/node_modules

and, also... if you're using zsh instead of bash you might want to edit the $PATH export to...

> echo 'export PATH="~/.npm-packages/bin:$PATH"' >> ~/.zshrc

**Comment by josephdburdick** [comment]
Thanks @therinken for addressing zshr users. :+1:

**Comment by hvtor** [comment]
@therinken No go.  Still having the same issue with the iron command. cc: @cmather

**Comment by therinken** [comment]
@hvtor ...I think you might want to also adjust your /etc/profile and /etc/zprofile files.....
If you go inside these files, find this block...
>if [ -x /usr/libexec/path_helper ]; then
>	eval `/usr/libexec/path_helper -s`
>fi

and edit it to...

>if [ -x /usr/libexec/path_helper ]; then
>	PATH=""
>	eval `/usr/libexec/path_helper -s`
>fi

the philosophy behind this suggestion cam be found at...

>http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper

...and, in my particular case, npm was installing global pkg's into a private node_modules directory, which was creating EACCES errors... the solution can be found here...

>https://docs.npmjs.com/getting-started/fixing-npm-permissions

...I chose option 2 and it worked beautifully! ...hope this helps!
